# Generated by Django 5.0.6 on 2026-06-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('project', models.CharField(choices=[('PRIV', 'Cloud Privado'), ('PUB', 'Cloud Público')], max_length=4)),
                ('phase', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=60)),
                ('layer', models.CharField(blank=True, max_length=40)),
                ('start', models.DateField()),
                ('due', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('done', 'Completada')], default='pending', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('depends', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due', 'code'],
            },
        ),
    ]
